repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: pwsh -NoProfile -Command "dotnet format"
        language: system
        pass_filenames: false
      - id: dotnet-build
        name: dotnet build
        entry: pwsh -NoProfile -Command "dotnet build \"TopstepX.Bot.sln\" -v minimal"
        language: system
        pass_filenames: false
      - id: dotnet-test
        name: dotnet test
        entry: pwsh -NoProfile -Command "dotnet test -v minimal"
        language: system
        pass_filenames: false
      - id: block-protected
        name: Block protected files
        entry: pwsh -NoProfile -Command "scripts\\hooks\\block-protected.ps1"
        language: system
        pass_filenames: true
