name: S11
label: Exhaustion
family: Reversal
bias: both
when:
  regime:
    - Trend
    - HighVol
  micro:
    - "climax.volume_thrust >= 1.5"
    - "mom.zscore <= -1.0 if intent==Long else >= 1.0"
confluence:
  - "pattern.kind: [PinBarBull, PinBarBear, BullishEngulfing, BearishEngulfing]"
  - "zone.test_count >= 2 and zone.pressure >= 0.6"
contra:
  - "zone.breakout_score >= 0.75"
playbook:
  entry: "limit_reversal at_zone_mid"
  bracket: "tp_mid_to_opposite_zone; sl_beyond_zone buffer_ticks: 8"
telemetryTags:
  - S11
  - Exhaustion