# Copilot Enterprise AI Configuration
version: 2.0

ai_settings:
  model: gpt-4-turbo
  temperature: 0.2
  max_tokens: 4000
  
confidence_thresholds:
  auto_fix: 0.85      # 85% confidence for auto-fix
  create_pr: 0.60     # 60% confidence for PR
  manual_review: 0.0  # Below 60% needs human

auto_fix_rules:
  workflow_errors: true
  dependency_issues: true
  config_problems: true
  code_errors: true
  
protected_files:
  - .github/workflows/copilot_ai_mechanic.yml
  - .github/copilot_mechanic/copilot_ai_brain.py
  
learning:
  enabled: true
  max_memory_entries: 1000
  pattern_recognition: true
  
notifications:
  on_fix: true
  on_failure: true
  on_learning: false

# GitHub Integration
github:
  organization: c-trading-bo
  repository: trading-bot-c-
  
# Enterprise Features
enterprise:
  unlimited_requests: true
  priority_processing: true
  advanced_models: true
  custom_knowledge_base: true
