# ES/NQ Critical Trading - OPTIMIZED for 50K Budget
name: ES/NQ Critical Trading (Budget Optimized)

"on":
  schedule:
    # OPTIMIZED SCHEDULE - 40% reduction with smart timing
    
    # HIGHEST PRIORITY: Market Open/Close (Every 5 min)
    - cron: '*/5 14-15 * * 1-5'         # Market open 9:30-10:30 AM EST
    - cron: '*/5 20-21 * * 1-5'         # Market close 3:00-4:00 PM EST
    
    # HIGH PRIORITY: Midday Trading (Every 15 min)
    - cron: '*/15 15-20 * * 1-5'        # Midday 10:30 AM - 3:00 PM EST
    
    # MEDIUM PRIORITY: Pre-market (Every 20 min)
    - cron: '*/20 13-14 * * 1-5'        # Pre-market 8:00-9:30 AM EST
    
    # LOW PRIORITY: After hours (Every 30 min)
    - cron: '*/30 21-23 * * 1-5'        # After hours until 6 PM EST
    
    # MINIMAL: Overnight (Every 2 hours)
    - cron: '0 */2 0-13 * * 1-5'        # Overnight coverage
    
    # Total: ~18 runs/day (vs 30 current) = 40% reduction
    
  workflow_dispatch:
    inputs:
      urgency:
        description: 'Trading urgency level'
        type: choice
        options:
        - normal
        - high
        - critical

env:
  OPTIMIZATION_LEVEL: "high_efficiency"
  MAX_RUNTIME_MINUTES: 15
  
jobs:
  es-nq-critical-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.MAX_RUNTIME_MINUTES }}
    
    steps:
    - name: 🎯 Optimized ES/NQ Critical Start
      run: |
        echo "📈 ES/NQ Critical Trading - Budget Optimized"
        echo "⚡ Focus: Maximum frequency during high-impact periods"
        echo "🎯 Strategy: 5min open/close, 15min midday, 30min after hours"
        echo "💰 Savings: 40% reduction while preserving critical timing"
