name: ES/NQ Correlation Matrix Analysis
"on":
  schedule:
    # 24/7 ES/NQ CORRELATION ANALYSIS (CRITICAL FOR FUTURES TRADING)
    # Asian Session (18:00-23:59 CT) - NQ dominance correlation tracking
    - cron: '0,30 0,1,2,3,4,5 * * *'    # Every 30 minutes Asian session
    # European Session (02:00-05:00 CT) - ES focus correlation analysis
    - cron: '15,45 8,9,10,11 * * *'     # Every 30 minutes European session
    # US Session (08:30-16:00 CT) - Maximum correlation monitoring
    - cron: '0,20,40 14,15,16,17,18,19,20,21 * * 1-5'  # Every 20 minutes US session
    # Extended Hours Correlation Monitoring  
    - cron: '10,50 6,7,12,13,22,23 * * *'  # 40-minute intervals extended hours
    # Total: ~48 runs/day = 336 runs/week for real-time correlation tracking
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  correlation_matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --retry-delays 1,2,3 --timeout 60 yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/correlations.py

      - name: "🔗 Integrate with BotCore Decision Engine"
        run: |
          echo "🔗 Converting ES/NQ Correlation Matrix analysis to BotCore format..."
          
          # Run data integration script for correlation data
          python Intelligence/scripts/workflow_data_integration.py \
            --workflow-type "es_nq_correlation_matrix" \
            --data-path "Intelligence/data/correlations.json" \
            --output-path "Intelligence/data/integrated/correlation_analysis.json"
          
          echo "✅ BotCore correlation matrix integration complete"

      - name: "📤 Commit Integrated Data"
        run: |
          git config --global user.email "ml-bot@github.com"
          git config --global user.name "ML Bot"
          git config user.name "GitHub Actions"
          git config --global user.email "ml-bot@github.com"
          git config --global user.name "ML Bot"
          git config user.email "actions@github.com"
          git config --global user.email "ml-bot@github.com"
          git config --global user.name "ML Bot"
          git add Intelligence/data/integrated/
          git add Intelligence/data/
          git diff --quiet || git commit -m "🔗 ES/NQ Correlation: BotCore-integrated matrix analysis $(date -u +%Y%m%d_%H%M%S)"
          git push --force-with-lease || git push --force-with-lease || echo "Push failed, continuing..."
