name: auto-label-automerge

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Add automerge label
        uses: actions/github-script@v7
        with:
          script: |
            const label = 'automerge';
            const {owner, repo} = context.repo;
            const issue_number = context.payload.pull_request.number;
            try {
              await github.rest.issues.addLabels({ owner, repo, issue_number, labels: [label] });
            } catch (e) {
              core.warning(`Failed to add label: ${e.message}`);
            }
