name: auto-label-automerge
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Add automerge label
      uses: actions/github-script@v7
      with:
        script: "const label = 'automerge';\nconst {owner, repo} = context.repo;\n\
          const issue_number = context.payload.pull_request.number;\ntry {\n  await\
          \ github.rest.issues.addLabels({ owner, repo, issue_number, labels: [label]\
          \ });\n} catch (e) {\n  core.warning(`Failed to add label: ${e.message}`);\n\
          }\n"
'on':
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
