name: .NET Bot CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

name: .NET Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          dotnet-version: '8.0.x'
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      with:
      name: .NET Build & Test
  build:
