name: "Cloud ML Training Pipeline"
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Manual trigger
  push:                    # Also run on any push
    branches: ['*']        # Run on any branch

jobs:
  cloud-training:
    runs-on: ubuntu-latest
    
    steps:
      - name: ≡ƒôÑ Checkout Code
        uses: actions/checkout@v4
        
      - name: ≡ƒÉì Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: ≡ƒôª Install ML Dependencies
        run: |
          pip install torch torchvision numpy pandas
          pip install stable-baselines3[extra]
          pip install scikit-learn matplotlib
          
      - name: "Download Training Data"
        run: |
          # Create directories
          mkdir -p data/rl_training models/rl
          
          # Download latest training data from previous releases
          gh release list --limit 5 | grep -E "training-data|models" | head -1 | while read line; do
            tag=$(echo $line | awk '{print $3}')
            echo "Downloading from release: $tag"
            gh release download $tag --pattern "*.tar.gz" -D ./downloads/ || echo "No previous training data"
          done
          
          # Extract training data if found
          if [ -f "./downloads/training-data.tar.gz" ]; then
            tar -xzf ./downloads/training-data.tar.gz -C data/rl_training/
            echo "Training data extracted"
          fi
          
      - name: "Train RL Models"
        run: |
          cd ml/rl
          python train_cvar_ppo.py --cloud-mode --data-path ../../data/rl_training/
          
      - name: "Upload Trained Models"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Package models and training data
          tar -czf models-$(date +%Y%m%d-%H%M).tar.gz models/rl/
          tar -czf training-data-$(date +%Y%m%d-%H%M).tar.gz data/rl_training/
          
          # Create release with trained models
          tag="cloud-training-$(date +%Y%m%d-%H%M)"
          gh release create "$tag" \
            --title "≡ƒñû Cloud Training - $(date)" \
            --notes "Automated cloud training run. Models updated every 6 hours." \
            models-*.tar.gz training-data-*.tar.gz
          
      - name: "Training Summary"
        run: |
          echo "≡ƒÄ» Cloud training completed successfully!"
          echo "≡ƒôê Models uploaded to GitHub releases"
          echo "≡ƒöä Next training in 6 hours"
          echo "≡ƒÆ╛ Models available for download by local bot"
