name: 🧠 Copilot Enterprise AI Mechanic

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed
  
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  
  workflow_dispatch:
    inputs:
      action:
        description: 'AI Action'
        required: true
        default: 'diagnose'
        type: choice
        options:
          - diagnose
          - fix
          - optimize
          - learn

jobs:
  copilot-ai-mechanic:
    name: AI Brain Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: write
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: 📦 Install Dependencies
        run: |
          pip install requests pyyaml
      
      - name: 🧠 Run AI Brain Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "🧠 Starting Copilot Enterprise AI Brain..."
          python .github/copilot_mechanic/copilot_ai_brain.py
      
      - name: 📊 Upload AI Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ai-brain-reports
          path: |
            .github/copilot_mechanic/fixes/
            .github/copilot_mechanic/knowledge/
          retention-days: 30
      
      - name: 📈 Update AI Status
        if: always()
        run: |
          echo "🎯 AI Brain analysis completed"
          echo "📊 Check artifacts for detailed reports"