name: COT Report Analysis
on:
  schedule:
  - cron: 0 21 * * 2
  - cron: 0 21 * * 5
  workflow_dispatch: null
jobs:
  cot_analysis:
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: pip
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pandas requests numpy yfinance beautifulsoup4 lxml

        '
    - name: Run COT Analysis
      run: 'cd Intelligence/scripts

        python cot_report.py

        '
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit COT data
      run: 'git config --local user.email "action@github.com"

        git config --local user.name "GitHub Action"

        git add data/cot/

        git diff --staged --quiet || git commit -m "🏛️ COT Report update: $(date +''%Y-%m-%d'')"

        git push

        '
    timeout-minutes: 15
    runs-on: ubuntu-latest
'on':
  workflow_dispatch: {}
