name: Intelligence - Daily Report

on:
  schedule:
    # Run before market open at 8:00 AM EST (13:00 UTC) on weekdays
    - cron: '0 13 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  generate-signals:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 🛡️ Prevent hanging
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 📥 Checkout Repository (Optimized)
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # ⚡ Speed: Only latest commit
      
    - name: 🐍 Setup Python with Caching
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'  # ⚡ Speed: Cache pip packages

    # ⚡ SPEED OPTIMIZATION: Cache Python dependencies
    - name: 💾 Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-daily_report-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-daily_report-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --quiet --no-warn-script-location --upgrade pip
        pip install --quiet --no-warn-script-location pandas numpy scikit-learn joblib requests
        
    - name: Generate trading signals
      run: |
        # ⚡ Speed: Timeout protection
        timeout 300 python Intelligence/scripts/generate_signals.py
        echo "Completed or timed out safely"
        
    - name: Generate daily report
      run: |
        # ⚡ Speed: Timeout protection
        timeout 300 python Intelligence/scripts/generate_daily_report.py
        echo "Completed or timed out safely"
        
    - name: Upload signals and reports
      uses: actions/upload-artifact@v4
      with:
        name: daily-intelligence-${{ github.run_number }}
        path: |
          Intelligence/data/signals/
          Intelligence/reports/
        retention-days: 30
        
    - name: Commit signals and reports (if changes)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Intelligence/data/signals/ Intelligence/reports/
        git diff --staged --quiet || git commit -m "Intelligence: Update signals and daily report [$(date '+%Y-%m-%d %H:%M:%S')]"
        git push
