name: Debug Simple Test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      
      - name: Debug Info
        run: |
          echo "Debug test completed successfully"
          echo "Timestamp: $(date -u)"