name: Build and Test

on:
  push:
    branches: [ main, master ]
  # REMOVED: pull_request trigger to prevent duplicate sessions with ultimate_build_ci_pipeline.yml
  # The comprehensive ultimate_build_ci_pipeline.yml handles PR builds

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore --verbosity minimal
      
    - name: Test core components
      run: |
        echo "Testing core components..."
        dotnet build SimpleBot/SimpleBot.csproj --no-restore
        dotnet test tests/SimpleBot.Tests/SimpleBot.Tests.csproj --no-restore --verbosity minimal
      
    - name: Run SimpleBot health check
      run: |
        echo "Running SimpleBot health check..."
        timeout 30s dotnet run --project SimpleBot/SimpleBot.csproj || true
        echo "Health check completed"
        
    - name: Verify build artifacts
      run: |
        echo "Verifying build output..."
        ls -la SimpleBot/bin/Debug/net8.0/
        echo "Build verification completed"