name: build
on:
  push: null
  pull_request: null
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  build:
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
    - uses: actions/setup-dotnet@v4
      with: null
    - run: dotnet restore
    - run: dotnet build --configuration Release --no-restore
    - run: dotnet test --configuration Release --no-build --verbosity normal
    runs-on: ubuntu-latest
'on':
  workflow_dispatch: {}
