name: Failed Patterns Detection
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  failed_patterns:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: pip
    - run: pip install --retry-delays 1,2,3 --timeout 60 yfinance pandas numpy scipy
        requests beautifulsoup4 ta pytrends fredapi
    - run: python Intelligence/scripts/failed_patterns.py
    - run: 'git config --global user.email "ml-bot@github.com"

        git config --global user.name "ML Bot"

        git config user.name "GitHub Actions"

        git config --global user.email "ml-bot@github.com"

        git config --global user.name "ML Bot"

        git config user.email "actions@github.com"

        git config --global user.email "ml-bot@github.com"

        git config --global user.name "ML Bot"

        git add Intelligence/data/

        git diff --quiet || git commit -m "Update failed patterns analysis"

        git push --force-with-lease || git push --force-with-lease || echo "Push failed,
        continuing..."'
'on':
  schedule:
  - cron: '*/20 13-21 * * 1-5'
  - cron: 0 0-12,22-23 * * 1-5
  - cron: 0 */4 * * 0,6
  workflow_dispatch: null
