name: Universal Dependency Installation Template
true:
  workflow_call: null
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: pip
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: '~/.cache/pip

          /usr/lib/libta_lib*

          /usr/include/ta-lib/

          '
        key: ${{ runner.os }}-comprehensive-deps-${{ hashFiles('**/requirements*.txt')
          }}
    - name: Install System Dependencies
      run: 'sudo apt-get update

        sudo apt-get install -y wget tar build-essential

        '
    - name: Install TA-Lib C Library (CRITICAL FIX)
      run: "if [ ! -f /usr/lib/libta_lib.so ]; then\n  echo \"\U0001F4CA Installing\
        \ TA-Lib C library from source...\"\n  wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz\n\
        \  tar -xzf ta-lib-0.4.0-src.tar.gz\n  cd ta-lib/\n  ./configure --prefix=/usr\n\
        \  make\n  sudo make install\n  cd ..\n  sudo ldconfig\n  echo \"\u2705 TA-Lib\
        \ C library installed successfully\"\nelse\n  echo \"\u2705 TA-Lib C library\
        \ already cached\"\nfi\n"
    - name: Install Complete Python Dependencies
      run: "pip install --retry-delays 1,2,3 --timeout 60 --upgrade pip\n\n# Core\
        \ dependencies\npip install --retry-delays 1,2,3 --timeout 60 numpy pandas\
        \ scipy\n\n# TA-Lib Python wrapper (AFTER C library)\npip install --retry-delays\
        \ 1,2,3 --timeout 60 TA-Lib\n\n# Backup technical analysis libraries\npip\
        \ install --retry-delays 1,2,3 --timeout 60 ta pandas-ta\n\n# Data collection\n\
        pip install --retry-delays 1,2,3 --timeout 60 yfinance feedparser requests\
        \ beautifulsoup4\n\n# ML/RL dependencies\npip install --retry-delays 1,2,3\
        \ --timeout 60 scikit-learn torch onnx onnxruntime\npip install --retry-delays\
        \ 1,2,3 --timeout 60 xgboost lightgbm catboost optuna\n\n# Additional utilities\
        \ (optional, with error handling)\npip install --retry-delays 1,2,3 --timeout\
        \ 60 textblob vaderSentiment || echo \"\u26A0\uFE0F Sentiment libraries optional\"\
        \npip install --retry-delays 1,2,3 --timeout 60 pytrends || echo \"\u26A0\uFE0F\
        \ Trends library optional\"\npip install --retry-delays 1,2,3 --timeout 60\
        \ fredapi || echo \"\u26A0\uFE0F FRED API optional\"\n"
    - name: Verify Installation
      run: "echo \"\U0001F9EA Testing critical dependencies...\"\npython -c \"import\
        \ pandas as pd; import numpy as np; print('\u2705 Core: pandas, numpy')\"\n\
        python -c \"import talib; print('\u2705 TA-Lib: Main library working')\" ||\
        \ echo \"\u26A0\uFE0F TA-Lib: Not available\"\npython -c \"import ta; print('\u2705\
        \ ta: Backup library working')\" || echo \"\u26A0\uFE0F ta: Not available\"\
        \  \npython -c \"import yfinance as yf; print('\u2705 yfinance: Data collection\
        \ working')\" || echo \"\u26A0\uFE0F yfinance: Not available\"\necho \"\U0001F389\
        \ Dependency verification complete!\""
