name: Universal Dependency Installation Template
on:
  workflow_call: null
permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  install-dependencies:
    timeout-minutes: 30
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: pip
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: '~/.cache/pip

          /usr/lib/libta_lib*

          /usr/include/ta-lib/

          '
        key: ${{ runner.os }}-comprehensive-deps-${{ hashFiles('**/requirements*.txt')
          }}
    - name: Install System Dependencies
      run: 'sudo apt-get update

        sudo apt-get install -y wget tar build-essential

        '
    - name: Install TA-Lib C Library (CRITICAL FIX)
      run: "if [ ! -f /usr/lib/libta_lib.so ]; then\n  echo \"\U0001F4CA Installing\
        \ TA-Lib C library from source...\"\n  wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz\n\
        \  tar -xzf ta-lib-0.4.0-src.tar.gz\n  cd ta-lib/\n  ./configure --prefix=/usr\n\
        \  make\n  sudo make install\n  cd ..\n  sudo ldconfig\n  echo \"✅ TA-Lib\
        \ C library installed successfully\"\nelse\n  echo \"✅ TA-Lib C library already\
        \ cached\"\nfi\n"
    - name: Install Complete Python Dependencies
      run: 'pip install --retry-delays 1,2,3 --timeout 60 --upgrade pip


        # Core dependencies

        pip install --retry-delays 1,2,3 --timeout 60 numpy pandas scipy


        # TA-Lib Python wrapper (AFTER C library)

        pip install --retry-delays 1,2,3 --timeout 60 TA-Lib


        # Backup technical analysis libraries

        pip install --retry-delays 1,2,3 --timeout 60 ta pandas-ta


        # Data collection

        pip install --retry-delays 1,2,3 --timeout 60 yfinance feedparser requests
        beautifulsoup4


        # ML/RL dependencies

        pip install --retry-delays 1,2,3 --timeout 60 scikit-learn torch onnx onnxruntime

        pip install --retry-delays 1,2,3 --timeout 60 xgboost lightgbm catboost optuna


        # Additional utilities (optional, with error handling)

        pip install --retry-delays 1,2,3 --timeout 60 textblob vaderSentiment || echo
        "⚠️ Sentiment libraries optional"

        pip install --retry-delays 1,2,3 --timeout 60 pytrends || echo "⚠️ Trends
        library optional"

        pip install --retry-delays 1,2,3 --timeout 60 fredapi || echo "⚠️ FRED API
        optional"

        '
    - name: Verify Installation
      run: "echo \"\U0001F9EA Testing critical dependencies...\"\npython -c \"import\
        \ pandas as pd; import numpy as np; print('✅ Core: pandas, numpy')\"\npython\
        \ -c \"import talib; print('✅ TA-Lib: Main library working')\" || echo \"\
        ⚠️ TA-Lib: Not available\"\npython -c \"import ta; print('✅ ta: Backup library\
        \ working')\" || echo \"⚠️ ta: Not available\"  \npython -c \"import yfinance\
        \ as yf; print('✅ yfinance: Data collection working')\" || echo \"⚠️ yfinance:\
        \ Not available\"\necho \"\U0001F389 Dependency verification complete!\""
    runs-on: ubuntu-latest
'on':
  workflow_dispatch: {}
