name: Universal Dependency Installation Template

# This workflow provides a reusable template for installing all dependencies
# Copy these steps to any workflow that needs ML/TA dependencies

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          /usr/lib/libta_lib*
          /usr/include/ta-lib/
        key: ${{ runner.os }}-comprehensive-deps-${{ hashFiles('**/requirements*.txt') }}
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar build-essential
    
    - name: Install TA-Lib C Library (CRITICAL FIX)
      run: |
        if [ ! -f /usr/lib/libta_lib.so ]; then
          echo "📊 Installing TA-Lib C library from source..."
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          sudo ldconfig
          echo "✅ TA-Lib C library installed successfully"
        else
          echo "✅ TA-Lib C library already cached"
        fi
    
    - name: Install Complete Python Dependencies
      run: |
        pip install --upgrade pip
        
        # Core dependencies
        pip install numpy pandas scipy
        
        # TA-Lib Python wrapper (AFTER C library)
        pip install TA-Lib
        
        # Backup technical analysis libraries
        pip install ta pandas-ta
        
        # Data collection
        pip install yfinance feedparser requests beautifulsoup4
        
        # ML/RL dependencies
        pip install scikit-learn torch onnx onnxruntime
        pip install xgboost lightgbm catboost optuna
        
        # Additional utilities (optional, with error handling)
        pip install textblob vaderSentiment || echo "⚠️ Sentiment libraries optional"
        pip install pytrends || echo "⚠️ Trends library optional"
        pip install fredapi || echo "⚠️ FRED API optional"
        
    - name: Verify Installation
      run: |
        echo "🧪 Testing critical dependencies..."
        python -c "import pandas as pd; import numpy as np; print('✅ Core: pandas, numpy')"
        python -c "import talib; print('✅ TA-Lib: Main library working')" || echo "⚠️ TA-Lib: Not available"
        python -c "import ta; print('✅ ta: Backup library working')" || echo "⚠️ ta: Not available"  
        python -c "import yfinance as yf; print('✅ yfinance: Data collection working')" || echo "⚠️ yfinance: Not available"
        echo "🎉 Dependency verification complete!"