name: Intelligence - Market Data

on:
  schedule:
    # Run after market close at 4:30 PM EST (21:30 UTC) on weekdays
    - cron: '30 21 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  collect-market-data:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy yfinance
        
    - name: Collect SPX/VIX/indices data
      run: |
        python Intelligence/scripts/collect_market_data.py
        
    - name: Upload market data
      uses: actions/upload-artifact@v4
      with:
        name: market-data-${{ github.run_number }}
        path: Intelligence/data/raw/indices/
        retention-days: 30
        
    - name: Commit market data (if changes)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Intelligence/data/raw/indices/
        git diff --staged --quiet || git commit -m "Intelligence: Update market data [$(date '+%Y-%m-%d %H:%M:%S')]"
        git push
