name: Intelligence - Market Data ⚡ (OPTIMIZED)

"on":
  schedule:
    - cron: '31 16 * * 1-5'
    - cron: '0 0,8,16 * * 0,6'

  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  collect-market-data:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # Shallow clone for speed
      
    # ⚡ SPEED OPTIMIZATION: Python + Dependencies Caching
    - name: Set up Python with caching
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    # ⚡ SPEED OPTIMIZATION: Cache dependencies
    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-market-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-market-
          ${{ runner.os }}-pip-
        
    # ⚡ SPEED OPTIMIZATION: Minimal dependency installation
    - name: Install dependencies (optimized)
      run: |
        python -m pip install --upgrade pip --quiet
        pip install requests pandas numpy yfinance --only-if-needed --quiet
        
    # ⚡ SPEED OPTIMIZATION: Parallel data collection
    - name: Collect market data (optimized)
      run: |
        # Run market data collection with timeout and error handling
        timeout 180 python Intelligence/scripts/collect_market_data.py || {
          echo "Market data collection timed out or failed - using cached data"
          exit 0
        }
        
    # ⚡ SPEED OPTIMIZATION: Conditional artifact upload
    - name: Upload market data (if new data)
      uses: actions/upload-artifact@v4
      if: hashFiles('Intelligence/data/raw/indices/*') != ''
      with:
        name: market-data-${{ github.run_number }}
        path: |
          Intelligence/data/raw/indices/*.csv
          Intelligence/data/raw/indices/*.json
        retention-days: 30

    # 🔗 BotCore Integration
    - name: "🔗 Integrate with BotCore Decision Engine"
      run: |
        echo "🔗 Converting Market Data to BotCore format..."
        
        # Run data integration script for market data
        python Intelligence/scripts/workflow_data_integration.py \
          --workflow-type "market_data" \
          --data-path "Intelligence/data/raw/indices/" \
          --output-path "Intelligence/data/integrated/market_data_feed.json"
        
        echo "✅ BotCore market data integration complete"
        
    # ⚡ SPEED OPTIMIZATION: Smart commit (only if changes)
    - name: "📤 Commit Integrated Market Data"
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Only commit if there are actual changes
        if [ -n "$(git status --porcelain Intelligence/)" ]; then
          git add Intelligence/data/integrated/ Intelligence/data/raw/indices/
          git commit -m "📊 Market Data: BotCore-integrated feed [$(date '+%Y-%m-%d %H:%M:%S')] ⚡"
          git push
        else
          echo "No new market data - skipping commit"
        fi

