name: "📊 Metrics Telemetry Pipeline"

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour
  workflow_dispatch:

concurrency:
  group: metrics-telemetry
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

env:
  RUNTIME_BUDGET: "60"  # 1 minute

jobs:
  metrics-telemetry:
    name: "Metrics Telemetry"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    
    steps:
      - name: "📥 Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: "🐍 Setup Python Environment"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: "📦 Install Dependencies"
        run: |
          pip install --upgrade pip
          pip install requests pandas pyarrow

      - name: "📊 Aggregate Workflow Metrics"
        run: |
          echo "📊 Aggregating workflow metrics..."
          python << 'EOF'
          import requests
          import json
          import os
          from datetime import datetime, timedelta
          
          print("[METRICS-TELEMETRY] 📊 Aggregating Workflow Metrics")
          
          # GitHub API to get workflow runs (simulated for demo)
          # In production, this would use actual GitHub API calls
          
          # Simulate workflow metrics
          workflows = [
              'data_feature_build.yml',
              'news_macro.yml', 
              'train_models.yml',
              'promote_manifest.yml',
              'backtest_sweep.yml',
              'regime_refresh.yml',
              'metrics_telemetry.yml',
              'qa_tests.yml',
              'build_ci.yml'
          ]
          
          # Simulate metrics for each workflow
          workflow_metrics = {}
          total_runtime_minutes = 0
          
          for workflow in workflows:
              # Simulate workflow run data
              if 'data_feature_build' in workflow:
                  runtime = 2.5
                  success_rate = 0.98
                  runs_per_day = 96  # Every 15 minutes
              elif 'news_macro' in workflow:
                  runtime = 2.8
                  success_rate = 0.95
                  runs_per_day = 6   # 6 times daily
              elif 'train_models' in workflow:
                  runtime = 280
                  success_rate = 0.92
                  runs_per_day = 3.4  # 3 times weekdays + Saturday
              elif 'promote_manifest' in workflow:
                  runtime = 3.2
                  success_rate = 0.97
                  runs_per_day = 3.4  # After each training
              elif 'backtest_sweep' in workflow:
                  runtime = 340
                  success_rate = 0.88
                  runs_per_day = 1   # Daily
              elif 'regime_refresh' in workflow:
                  runtime = 6.5
                  success_rate = 0.99
                  runs_per_day = 4   # Every 6 hours
              elif 'metrics_telemetry' in workflow:
                  runtime = 0.8
                  success_rate = 0.99
                  runs_per_day = 24  # Hourly
              elif 'qa_tests' in workflow:
                  runtime = 10
                  success_rate = 0.94
                  runs_per_day = 1   # Daily
              elif 'build_ci' in workflow:
                  runtime = 5
                  success_rate = 0.96
                  runs_per_day = 2   # Varies with PRs
              
              daily_runtime = runtime * runs_per_day
              total_runtime_minutes += daily_runtime
              
              workflow_metrics[workflow] = {
                  'avg_runtime_minutes': runtime,
                  'success_rate': success_rate,
                  'runs_per_day': runs_per_day,
                  'daily_runtime_minutes': daily_runtime,
                  'monthly_runtime_minutes': daily_runtime * 30,
                  'last_run_status': 'success' if success_rate > 0.9 else 'failure',
                  'efficiency_score': success_rate * (1 - runtime / 360)  # Penalize long runtimes
              }
          
          # Calculate resource utilization
          monthly_limit = 50000  # GitHub Actions limit
          monthly_usage = total_runtime_minutes * 30
          utilization_percentage = (monthly_usage / monthly_limit) * 100
          
          # Overall system metrics
          system_metrics = {
              'timestamp': datetime.utcnow().isoformat(),
              'total_workflows': len(workflows),
              'daily_runtime_minutes': total_runtime_minutes,
              'monthly_runtime_minutes': monthly_usage,
              'monthly_limit_minutes': monthly_limit,
              'utilization_percentage': utilization_percentage,
              'efficiency_target': 95.0,
              'utilization_status': 'optimal' if utilization_percentage < 95 else 'over_budget',
              'avg_success_rate': sum(w['success_rate'] for w in workflow_metrics.values()) / len(workflow_metrics),
              'overall_health': 'healthy' if utilization_percentage < 95 and sum(w['success_rate'] for w in workflow_metrics.values()) / len(workflow_metrics) > 0.95 else 'needs_attention'
          }
          
          # Performance trends (simulated)
          performance_trends = {
              'last_24h': {
                  'total_runs': 150,
                  'successful_runs': 142,
                  'failed_runs': 8,
                  'avg_runtime': 12.5,
                  'runtime_trend': 'stable'
              },
              'last_7d': {
                  'total_runs': 1050,
                  'successful_runs': 998,
                  'failed_runs': 52,
                  'avg_runtime': 12.8,
                  'runtime_trend': 'improving'
              },
              'last_30d': {
                  'total_runs': 4500,
                  'successful_runs': 4275,
                  'failed_runs': 225,
                  'avg_runtime': 13.2,
                  'runtime_trend': 'stable'
              }
          }
          
          # Alerts and recommendations
          alerts = []
          recommendations = []
          
          if utilization_percentage > 95:
              alerts.append({
                  'severity': 'high',
                  'message': f'Resource utilization at {utilization_percentage:.1f}% - exceeds 95% target',
                  'action_required': 'Optimize workflow runtimes or reduce frequency'
              })
          
          if system_metrics['avg_success_rate'] < 0.95:
              alerts.append({
                  'severity': 'medium',
                  'message': f'Average success rate {system_metrics["avg_success_rate"]:.3f} below 95% target',
                  'action_required': 'Investigate failing workflows'
              })
          
          # Workflow-specific recommendations
          for workflow, metrics in workflow_metrics.items():
              if metrics['success_rate'] < 0.9:
                  recommendations.append(f'{workflow}: Success rate {metrics["success_rate"]:.3f} - investigate failures')
              if metrics['avg_runtime_minutes'] > 300 and 'train_models' not in workflow and 'backtest' not in workflow:
                  recommendations.append(f'{workflow}: Runtime {metrics["avg_runtime_minutes"]:.1f}min - consider optimization')
          
          # Compile comprehensive telemetry
          telemetry_data = {
              'timestamp': datetime.utcnow().isoformat(),
              'system_metrics': system_metrics,
              'workflow_metrics': workflow_metrics,
              'performance_trends': performance_trends,
              'alerts': alerts,
              'recommendations': recommendations,
              'dashboard_url': 'https://github.com/c-trading-bo/trading-bot-c-/actions',
              'monitoring_status': 'active'
          }
          
          # Save telemetry data
          os.makedirs('telemetry', exist_ok=True)
          with open('telemetry/system_metrics.json', 'w') as f:
              json.dump(telemetry_data, f, indent=2)
          
          # Create dashboard summary
          dashboard_summary = {
              'last_updated': datetime.utcnow().isoformat(),
              'system_health': system_metrics['overall_health'],
              'utilization': f"{utilization_percentage:.1f}%",
              'success_rate': f"{system_metrics['avg_success_rate']:.3f}",
              'active_alerts': len(alerts),
              'total_workflows': len(workflows),
              'daily_runtime': f"{total_runtime_minutes:.1f} minutes"
          }
          
          with open('telemetry/dashboard_summary.json', 'w') as f:
              json.dump(dashboard_summary, f, indent=2)
          
          print(f"[METRICS-TELEMETRY] ✅ System health: {system_metrics['overall_health']}")
          print(f"[METRICS-TELEMETRY] 📊 Utilization: {utilization_percentage:.1f}% of monthly limit")
          print(f"[METRICS-TELEMETRY] 📈 Success rate: {system_metrics['avg_success_rate']:.3f}")
          print(f"[METRICS-TELEMETRY] 🚨 Alerts: {len(alerts)}")
          
          EOF

      - name: "📈 Generate Performance Dashboard"
        run: |
          echo "📈 Generating performance dashboard..."
          python << 'EOF'
          import json
          import os
          from datetime import datetime
          
          print("[DASHBOARD] 📈 Generating Performance Dashboard")
          
          # Load telemetry data
          with open('telemetry/system_metrics.json', 'r') as f:
              telemetry = json.load(f)
          
          # Generate dashboard HTML (simplified)
          dashboard_html = f"""
          <!DOCTYPE html>
          <html>
          <head>
              <title>Trading Bot Metrics Dashboard</title>
              <style>
                  body {{ font-family: Arial, sans-serif; margin: 20px; }}
                  .metric {{ display: inline-block; margin: 10px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }}
                  .healthy {{ background-color: #d4edda; }}
                  .warning {{ background-color: #fff3cd; }}
                  .critical {{ background-color: #f8d7da; }}
              </style>
          </head>
          <body>
              <h1>🤖 Trading Bot System Dashboard</h1>
              <p>Last Updated: {telemetry['timestamp']}</p>
              
              <h2>System Health</h2>
              <div class="metric {'healthy' if telemetry['system_metrics']['overall_health'] == 'healthy' else 'warning'}">
                  <strong>Overall Health:</strong> {telemetry['system_metrics']['overall_health'].title()}
              </div>
              
              <div class="metric {'healthy' if telemetry['system_metrics']['utilization_percentage'] < 95 else 'critical'}">
                  <strong>Resource Utilization:</strong> {telemetry['system_metrics']['utilization_percentage']:.1f}%
              </div>
              
              <div class="metric {'healthy' if telemetry['system_metrics']['avg_success_rate'] > 0.95 else 'warning'}">
                  <strong>Success Rate:</strong> {telemetry['system_metrics']['avg_success_rate']:.3f}
              </div>
              
              <h2>Workflow Performance</h2>
              <table border="1" style="border-collapse: collapse; width: 100%;">
                  <tr>
                      <th>Workflow</th>
                      <th>Runtime (min)</th>
                      <th>Success Rate</th>
                      <th>Runs/Day</th>
                      <th>Daily Usage (min)</th>
                  </tr>
          """
          
          for workflow, metrics in telemetry['workflow_metrics'].items():
              status_class = 'healthy' if metrics['success_rate'] > 0.95 else 'warning'
              dashboard_html += f"""
                  <tr class="{status_class}">
                      <td>{workflow}</td>
                      <td>{metrics['avg_runtime_minutes']:.1f}</td>
                      <td>{metrics['success_rate']:.3f}</td>
                      <td>{metrics['runs_per_day']:.1f}</td>
                      <td>{metrics['daily_runtime_minutes']:.1f}</td>
                  </tr>
              """
          
          dashboard_html += """
              </table>
              
              <h2>Alerts</h2>
          """
          
          if telemetry['alerts']:
              for alert in telemetry['alerts']:
                  dashboard_html += f"""
                  <div class="metric {'warning' if alert['severity'] == 'medium' else 'critical'}">
                      <strong>{alert['severity'].upper()}:</strong> {alert['message']}<br>
                      <em>Action: {alert['action_required']}</em>
                  </div>
                  """
          else:
              dashboard_html += '<div class="metric healthy">No active alerts</div>'
          
          dashboard_html += """
              </body>
          </html>
          """
          
          # Save dashboard
          with open('telemetry/dashboard.html', 'w') as f:
              f.write(dashboard_html)
          
          print("[DASHBOARD] ✅ Performance dashboard generated")
          
          EOF

      - name: "🔔 Check Alert Conditions"
        run: |
          echo "🔔 Checking alert conditions..."
          python << 'EOF'
          import json
          
          print("[ALERTS] 🔔 Checking Alert Conditions")
          
          # Load telemetry data
          with open('telemetry/system_metrics.json', 'r') as f:
              telemetry = json.load(f)
          
          alerts = telemetry['alerts']
          
          if alerts:
              print(f"[ALERTS] 🚨 {len(alerts)} active alerts:")
              for alert in alerts:
                  print(f"  {alert['severity'].upper()}: {alert['message']}")
          else:
              print("[ALERTS] ✅ No active alerts - system operating normally")
          
          # Set GitHub output for potential notification
          if alerts:
              high_priority_alerts = [a for a in alerts if a['severity'] == 'high']
              if high_priority_alerts:
                  print("::warning::High priority alerts detected - immediate attention required")
              else:
                  print("::notice::Medium priority alerts detected - monitoring required")
          
          EOF

      - name: "📦 Upload Telemetry Data"
        uses: actions/upload-artifact@v4
        with:
          name: telemetry-${{ github.run_number }}
          path: telemetry/
          retention-days: 7

      - name: "✅ Telemetry Summary"
        run: |
          echo "✅ Metrics Telemetry Pipeline Complete"
          echo "📊 Workflow metrics aggregated from 9 consolidated workflows"
          echo "📈 Performance dashboard generated"
          echo "🔔 Alert conditions checked"
          echo "💾 Telemetry data stored for monitoring"
          echo "⏱️ Runtime: Under 1 minute budget"