name: Microstructure Analysis
on:
  schedule:
    - cron: '*/5 9-15 * * 1-5'  # Every 5 min RTH (9 AM - 3 PM UTC, Mon-Fri)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  microstructure:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install --retry-delays 1,2,3 --timeout 60 yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/microstructure.py
      - run: |
          git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git config user.name "GitHub Actions"
          git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git config user.email "actions@github.com"
          git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git add Intelligence/data/
          git diff --quiet || git commit -m "Update microstructure analysis"
          git push --force-with-lease || git push --force-with-lease || echo "Push failed, continuing..."