name: Microstructure Analysis
"on":
  schedule:
    - cron: '*/5 9:30-10:30,14:30-16 * * 1-5'
    - cron: '*/10 10:30-14:30 * * 1-5'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  microstructure:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/microstructure.py

      - name: "🔗 Integrate with BotCore Decision Engine"
        run: |
          echo "🔗 Converting Microstructure analysis to BotCore format..."
          
          # Run data integration script for microstructure data
          python Intelligence/scripts/workflow_data_integration.py \
            --workflow-type "microstructure" \
            --data-path "Intelligence/data/microstructure.json" \
            --output-path "Intelligence/data/integrated/microstructure_analysis.json"
          
          echo "✅ BotCore microstructure integration complete"

      - name: "📤 Commit Integrated Data"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Intelligence/data/integrated/
          git add Intelligence/data/
          git diff --quiet || git commit -m "🔬 Microstructure: BotCore-integrated analysis $(date -u +%Y%m%d_%H%M%S)"
          git push || echo "No changes to push"

