name: Minimal Debug

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  minimal-debug:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Minimal Debug
        run: |
          echo "Minimal debug test passed"
          echo "GitHub Actions environment ready"