name: Intelligence - ML Trainer

on:
  schedule:
    # Run nightly at 2:00 AM EST (07:00 UTC)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  train-models:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install ML dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn xgboost lightgbm joblib
        
    - name: Build features from raw data
      run: |
        python Intelligence/scripts/build_features.py
        
    - name: Train ML models
      run: |
        python Intelligence/scripts/train_models.py
        
    - name: Upload trained models
      uses: actions/upload-artifact@v4
      with:
        name: ml-models-${{ github.run_number }}
        path: Intelligence/models/
        retention-days: 90
        
    - name: Commit models and features (if changes)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Intelligence/data/features/ Intelligence/models/
        git diff --staged --quiet || git commit -m "Intelligence: Update ML models and features [$(date '+%Y-%m-%d %H:%M:%S')]"
        git push
