name: Intelligence - News Pulse

on:
  schedule:
    # Run every 5 minutes during market hours (9:30 AM - 4:00 PM ET on weekdays)
    - cron: '*/5 13-21 * * 1-5'  # UTC time for ET market hours
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  collect-news:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --retry-delays 1,2,3 --timeout 60 --upgrade pip
        pip install --retry-delays 1,2,3 --timeout 60 requests pandas numpy gdelt beautifulsoup4
        
    - name: Collect GDELT news data
      run: |
        python Intelligence/scripts/collect_news.py
        
    - name: Upload news data
      uses: actions/upload-artifact@v4
      with:
        name: news-data-${{ github.run_number }}
        path: Intelligence/data/raw/news/
        retention-days: 7
        
    - name: Commit news data (if changes)
      run: |
        git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git config --local user.email "action@github.com"
        git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git config --local user.name "GitHub Action"
        git config --global user.email "ml-bot@github.com"
        git config --global user.name "ML Bot"
        git add Intelligence/data/raw/news/
        git diff --staged --quiet || git commit -m "Intelligence: Update news data [$(date '+%Y-%m-%d %H:%M:%S')]"
        git push --force-with-lease || git push --force-with-lease || echo "Push failed, continuing..."