name: OPEX Calendar Tracking
on:
  schedule:
    - cron: '0 10 * * 1'  # Mondays 10:00 UTC
  workflow_dispatch:


permissions:
  contents: write

jobs:
  opex_calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/opex_tracker.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Intelligence/data/
          git diff --quiet || git commit -m "Update OPEX calendar tracking"
          git push
