name: Overnight Session Analysis
on:
  schedule:
    # OPTIMIZED OVERNIGHT (TIER 4)
    - cron: '0 22 * * 1-4'  # Weeknights at 5 PM EST (after market close)
    # Total: 4 runs/week
  workflow_dispatch:


permissions:
  contents: write

jobs:
  overnight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/overnight_analysis.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Intelligence/data/
          git diff --quiet || git commit -m "Update overnight session analysis"
          git push
