name: Quality Assurance
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  quality-check:
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v4
      with:
        cache: pip
    - name: Install QA tools
      run: 'pip install flake8 black pylint

        '
    - name: Run linting
      run: 'echo "Add linting commands here"

        # flake8 . || true

        # black --check . || true

        '