name: Regime Detection Analysis
on:
  schedule:
    - cron: '0 * * * *'  # Hourly (24/7)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  regime_detector:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies with Retry
        run: |
          for i in {1..3}; do
            pip install --upgrade pip && \
            pip install --timeout 60 yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi && break
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          done
          
      - name: Run Regime Detection
        run: |
          python Intelligence/scripts/regime_detector.py || echo "Regime detection completed with warnings"
          
      - name: Commit Results
        run: |
          git config --local user.email "ml-bot@github.com"
          git config --local user.name "ML Bot"
          git add Intelligence/data/ || echo "No data changes to add"
          git diff --staged --quiet || git commit -m "🔍 Regime detection analysis $(date -u +'%Y-%m-%d %H:%M')"
          git push --force-with-lease || echo "Push failed, continuing..."