name: Simple ML Test
on:
  workflow_dispatch: null

permissions:
  contents: write
  pull-requests: write
  actions: read
jobs:
  ml-test:
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: pip
    - name: Simple ML Test
      run: 'python -c "import sys; print(f''Python {sys.version} ready for ML'')"

        echo "Simple ML test completed successfully"'