name: "24/7 GitHub-Only ML/RL Training"

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      manual_test:
        description: "Run lightweight smoke tests"
        required: false
        default: false
        type: boolean
      force_run:
        description: "Force run even if recent models exist"
        required: false
        default: false
        type: boolean
  push:
    branches: ['main']

concurrency:
  group: train-github-only
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: read

env:
  VENDOR_DIR: "data/vendor"
  DATA_DIR: "data/logs"

jobs:
  continuous-training:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    permissions:
      contents: write
      
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
        
      - name: "🔍 Debug Workflow Info"
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Manual test: ${{ inputs.manual_test }}"
          echo "Force run: ${{ inputs.force_run }}"
          echo "Ref: ${{ github.ref }}"
        
      - name: "🐍 Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: "📦 Install Python Dependencies"
        run: |
          pip install --upgrade pip
          pip install torch numpy pandas scikit-learn onnx skl2onnx packaging pyarrow
          pip install gym stable-baselines3 tensorboard matplotlib seaborn
          pip install optuna hyperopt joblib
          
      - name: "🔍 Test Dependencies"  
        run: |
          python -c "import pandas as pd; import numpy as np; import torch; import onnx; import pyarrow; print('✅ All dependencies working')"

      - name: "🧪 Lightweight Smoke Test"
        if: ${{ inputs.manual_test == true }}
        run: |
          echo "🧪 Running lightweight smoke test..."
          mkdir -p models/rl data/logs
          python -c "
          import pandas as pd
          import numpy as np
          data = pd.DataFrame({
              'feature1': np.random.randn(10),
              'feature2': np.random.randn(10),
              'target': np.random.randn(10)
          })
          data.to_parquet('data/logs/test_data.parquet')
          print('✅ Smoke test completed successfully!')
          "

      - name: "📊 Generate Training Data"
        if: ${{ inputs.manual_test != true }}
        run: |
          mkdir -p models/rl data/logs data/vendor Intelligence/data/training
          echo "Creating training data..."
          python -c "
          import json
          import pandas as pd
          import numpy as np
          from datetime import datetime, timedelta
          
          # Generate training data
          meta_data = []
          for i in range(1000):
              meta_data.append({
                  'timestamp': (datetime.now() - timedelta(hours=i)).isoformat(),
                  'symbol': 'ES',
                  'price': 4500 + np.random.randn() * 50,
                  'volume': np.random.randint(1000, 10000),
                  'returns': np.random.randn() * 0.01,
                  'volatility': np.random.exponential(0.02)
              })
          
          df_meta = pd.DataFrame(meta_data)
          df_meta.to_csv('Intelligence/data/training/data.csv', index=False)
          print(f'Generated training data: {len(df_meta)} samples')
          "

      - name: "🤖 Train Models"
        if: ${{ inputs.manual_test != true }}
        run: |
          echo "Training models..."
          python ml/rl/train_cvar_ppo.py --data Intelligence/data/training/data.csv --save_dir models/rl/

      - name: "📦 Package Models"
        run: |
          mkdir -p models
          cd models
          timestamp=$(date +%Y%m%d-%H%M%S)
          tar -czf ml-models-${timestamp}.tar.gz rl/ 2>/dev/null || echo "No models to package"
          echo "MODEL_PACKAGE=ml-models-${timestamp}.tar.gz" >> $GITHUB_ENV
          echo "RELEASE_TAG=models-v${timestamp}" >> $GITHUB_ENV

      - name: "🚀 Create GitHub Release"
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: "AI Models $(date +'%Y-%m-%d %H:%M')"
          body: |
            🚀 **ML/RL Model Release**
            
            **Training Completed**: $(date +'%Y-%m-%d %H:%M:%S UTC')
            
            ## 🧠 **Models Included**:
            - **CVaR PPO Agent** - Advanced RL position sizing
            
            Download the `ml-models-*.tar.gz` file to get all trained models.
          draft: false
          prerelease: false

      - name: "📤 Upload Models to Release"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: models/${{ env.MODEL_PACKAGE }}
          asset_name: ${{ env.MODEL_PACKAGE }}
          asset_content_type: application/gzip

      - name: "✅ Training Complete"
        run: |
          echo "🎉 24/7 GitHub Learning Complete!"
          echo "📊 Models uploaded to: ${{ steps.create_release.outputs.html_url }}"
