name: Volatility Surface Analysis
on:
  schedule:
    # 24/7 VOLATILITY SURFACE MONITORING (CRITICAL FOR OPTIONS TRADING)
    # Asian Session (18:00-23:59 CT) - Monitor crypto/futures volatility
    - cron: '0 0,2,4 * * *'              # Every 2 hours Asian session
    # European Session (02:00-05:00 CT) - Monitor FX/indices volatility  
    - cron: '30 8,9,10,11 * * *'         # Every hour European session
    # US Session (08:30-16:00 CT) - Maximum volatility monitoring
    - cron: '0,30 14,15,16,17,18,19,20,21 * * 1-5'  # Every 30 minutes US session
    # After Hours Volatility Monitoring
    - cron: '15 6,7,12,13,22,23 * * *'   # Extended hours coverage
    # Total: ~27 runs/day = 189 runs/week for continuous volatility analysis
  workflow_dispatch:


permissions:
  contents: write

jobs:
  volatility_surface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/volatility_surface.py

      - name: "🔗 Integrate with BotCore Decision Engine"
        run: |
          echo "🔗 Converting Volatility Surface analysis to BotCore format..."
          
          # Run data integration script for volatility surface data
          python Intelligence/scripts/workflow_data_integration.py \
            --workflow-type "volatility_surface" \
            --data-path "Intelligence/data/volatility_surface.json" \
            --output-path "Intelligence/data/integrated/volatility_surface_analysis.json"
          
          echo "✅ BotCore volatility surface integration complete"

      - name: "📤 Commit Integrated Data"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Intelligence/data/integrated/
          git add Intelligence/data/
          git diff --quiet || git commit -m "📈 Volatility Surface: BotCore-integrated analysis $(date -u +%Y%m%d_%H%M%S)"
          git push || echo "No changes to push"
