name: Supply Demand Zones Identifier
"on":
  schedule:
    - cron: '15 8,11,14,17 * * 1-5'
    - cron: '0 10 * * 0,6'

  workflow_dispatch:


permissions:
  contents: write

jobs:
  zones_identifier:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas numpy scipy requests beautifulsoup4 ta pytrends fredapi
      - run: python Intelligence/scripts/identify_zones.py

      - name: "🔗 Integrate with BotCore Decision Engine"
        run: |
          echo "🔗 Converting Supply/Demand Zones analysis to BotCore format..."
          
          # Run data integration script for zones data
          python Intelligence/scripts/workflow_data_integration.py \
            --workflow-type "zones_identifier" \
            --data-path "Intelligence/data/zones.json" \
            --output-path "Intelligence/data/integrated/supply_demand_zones.json"
          
          echo "✅ BotCore zones integration complete"

      - name: "📤 Commit Integrated Data"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Intelligence/data/integrated/
          git add Intelligence/data/
          git diff --quiet || git commit -m "🎯 Supply/Demand Zones: BotCore-integrated analysis $(date -u +%Y%m%d_%H%M%S)"
          git push || echo "No changes to push"

